# Generated by Django 5.2.7 on 2025-10-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description_short',
        ),
    ]
