# Generated by Django 5.2.7 on 2025-10-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_place_description_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='description',
        ),
    ]
