# Generated by Django 5.2.7 on 2025-10-21 11:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_description_long_place_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
